# Generated by Django 2.1.4 on 2018-12-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('forecast', '0001_initial'),
        ('place', '0001_initial'),
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('batch_id', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Area')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.Category')),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.Feature')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Location')),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='response.AffectiveResponse')),
                ('weather', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.Weather')),
            ],
            options={
                'verbose_name_plural': 'master model',
            },
        ),
    ]
