# Generated by Django 2.1.4 on 2018-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='batch_id',
            field=models.IntegerField(default=0),
        ),
    ]
