# Generated by Django 2.1.4 on 2018-12-10 20:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectiveresponse',
            name='feature_set',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Superstitious')], default=0, max_length=20),
        ),
    ]
