# Generated by Django 2.1.4 on 2018-12-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0002_remove_affectiveresponse_feature_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectiveresponse',
            name='longevity',
            field=models.IntegerField(choices=[(1, 'One day'), (2, 'Two to four days'), (3, 'Five to seven days'), (4, 'More than seven days')], default=0),
            preserve_default=False,
        ),
    ]
