# Generated by Django 2.1.4 on 2018-12-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='bottom_south_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='area',
            name='left_west_long',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='area',
            name='right_east_long',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='area',
            name='top_north_lat',
            field=models.FloatField(default=0.0),
        ),
    ]
