# Generated by Django 2.1.4 on 2018-12-13 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20181214_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='bottom_south_lat',
            new_name='bottom_south_lat_TL',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='left_west_long',
            new_name='left_west_long_TL',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='right_east_long',
            new_name='right_east_long_TP',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='top_north_lat',
            new_name='top_north_lat_TP',
        ),
    ]
