# Generated by Django 2.1.4 on 2018-12-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20181214_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='status',
            field=models.BooleanField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
    ]
